### ISSUE TITLE
Player abilities

### ISSUE THREAD

**Issue by Miknielsen** [Miknielsen/OOSE2015_MiniProject#4]
Objects can move through player:
     -Implement edge detection to check whenever an object touches the player.

Player lives:
     -Implement lives for the player, preferably 3.
     -Implement edge detection on the bottom of the window to check if the ball has passed the player.
          -Decrease the life by 1.
          -When the player lives reaches 0 the game should end.

**Comment by nicfol** [comment]
The player can move freely on a fixed y-axis. However, it only has one life as multiple would make it too easy.
